[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "tea"
version = "0.3.0"
description = "Manage tmuxp session configurations"
authors = ["Kiyoshi '13k' Murata <kbmurata@gmail.com>"]

[tool.poetry.scripts]
tea = 'tea:main'

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^3.13"
tmuxp = "^1.7.2"

[tool.poetry.dev-dependencies]
pylint = "*"
black = {version = "*", allow-prereleases = true}
isort = "*"
mypy = "*"
ptpython = "*"

[tool.isort]
profile = "black"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "88"
